# -*- coding: utf-8 -*-
"""weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUj9gqrd1PON04L2qRr2GisYybP4ra2B
"""

from google.colab import drive
drive.mount("/content/gdrive")

folder_path = '/content/weather_classification_data.csv'

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier



data = pd.read_csv(folder_path)
data.head()

data.info()

data.describe()

data.groupby(["Weather Type"]).count()

sns.pairplot(data=data, hue="Weather Type")

print(data["Weather Type"].nunique())
print(data["Weather Type"].unique())

"""Tham khảo ở đây nhé https://www.kaggle.com/code/niketasengar/weather-type-classification#Correlation-Analysis"""